import { EventResume } from '../../domains/cbc-site/interfaces/Events/IEvents';
import championshipBMXImage from '../../assets/images/Events/championshipBMX.jpg';
import championshipDHIImage from '../../assets/images/Events/championshipDHI.jpg';
import paraCycling from '../../assets/images/Events/para-cycling.png';

export const eventItems: EventResume[] = [
  {
    id: '1',
    title: 'Campeonato Brasileiro de BMX Racing 2025',
    date: '03 de setembro',
    type: 'Competição',
    modalitySlug: 'bmx-racing',
    location: 'Salvador/BA',
    image: championshipBMXImage,
    color: 'typeText.secondary',
    limitDate: '12 de setembro',
    content:
      'Campeonato Brasileiro de BMX Racing com etapas nacionais e premiações. Mais informações em breve.',
  },
  {
    id: '2',
    title: 'Oeste de BMX',
    date: '06 de setembro',
    type: 'Evento',
    modalitySlug: 'bmx-freestyle',
    image: championshipDHIImage,
    location: 'Salvador/BA',
    color: 'typeText.tertiary',
    limitDate: '04 de setembro',
    content:
      'Evento regional de BMX com práticas e categorias amadoras e profissionais.',
  },
  {
    id: '3',
    title: 'Campeonato Brasileiro de BMX Racing 2025',
    date: '27 de setembro',
    type: 'Competição',
    modalitySlug: 'bmx-racing',
    location: 'Salvador/BA',
    image: paraCycling,
    color: 'typeText.secondary',
    limitDate: '20 de setembro',
    content: 'Fase final do Campeonato Brasileiro de BMX Racing 2025.',
  },
  {
    id: '4',
    title: 'Campeonato Brasileiro de BMX Racing 2025',
    date: '27 de setembro',
    type: 'Competição',
    modalitySlug: 'bmx-racing',
    location: 'Salvador/BA',
    image: paraCycling,
    color: 'typeText.secondary',
    limitDate: '20 de setembro',
    content: 'Fase final do Campeonato Brasileiro de BMX Racing 2025.',
  },
  {
    id: '5',
    title: 'Encontro Regional de Ciclismo de Estrada',
    date: '10 de novembro',
    type: 'Evento',
    modalitySlug: 'estrada',
    location: 'Curitiba/PR',
    image: championshipBMXImage,
    color: 'typeText.primary',
    limitDate: '01 de novembro',
    content:
      'Encontro com pedaladas guiadas, palestras e ações de segurança viária para ciclistas de estrada.',
  },
  {
    id: '6',
    title: 'Copa Nacional de DHI',
    date: '18 de novembro',
    type: 'Competição',
    modalitySlug: 'downhill',
    location: 'Belo Horizonte/MG',
    image: championshipDHIImage,
    color: 'typeText.secondary',
    limitDate: '10 de novembro',
    content:
      'Provas de downhill com categorias amadoras e profissionais, premiação e transmissão ao vivo.',
  },
  {
    id: '7',
    title: 'Festival de Paracicling',
    date: '25 de novembro',
    type: 'Evento',
    modalitySlug: 'paraciclismo',
    location: 'São Paulo/SP',
    image: paraCycling,
    color: 'typeText.tertiary',
    limitDate: '15 de novembro',
    content:
      'Festival inclusivo com apresentações, oficinas e competições de paracicling.',
  },
  {
    id: '8',
    title: 'Circuito MTB Conquista',
    date: '02 de dezembro',
    type: 'Competição',
    modalitySlug: 'mtb',
    location: 'Gramado/RS',
    image: championshipBMXImage,
    color: 'typeText.secondary',
    limitDate: '24 de novembro',
    content: 'Etapa final do circuito de MTB com provas XCO e XCM.',
  },
  {
    id: '9',
    title: 'Workshop Técnico de BMX Freestyle',
    date: '08 de dezembro',
    type: 'Evento',
    modalitySlug: 'bmx-freestyle',
    location: 'Porto Alegre/RS',
    image: championshipDHIImage,
    color: 'typeText.primary',
    limitDate: '01 de dezembro',
    content:
      'Workshop com técnicos e atletas para desenvolvimento de técnicas e segurança no BMX Freestyle.',
  },
  {
    id: '10',
    title: 'Passeio Ciclístico Solidário',
    date: '15 de dezembro',
    type: 'Evento',
    modalitySlug: 'lazer',
    location: 'Recife/PE',
    image: paraCycling,
    color: 'typeText.tertiary',
    limitDate: '10 de dezembro',
    content:
      'Passeio ciclístico com arrecadação de alimentos e atividades para famílias.',
  },
];
